config/routes.rb
Rails.application.routes.draw do
  root 'characters#index'
  resources :characters
  namespace :character do
    get '/:id/items/new', to: 'items#new', as: 'new_item'
    post '/:id/items/new', to: 'items#create', as: 'items'
    get '/:id/powers/new', to: 'powers#new', as: 'new_power'
    post '/:id/powers/new', to: 'powers#create', as: 'powers'
  end
end

app/models/character.rb
class Character < ActiveRecord::Base
  has_many :items
  has_many :powers

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :character
end

app/models/power.rb
class Power < ActiveRecord::Base
  belongs_to :character
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/character/items_controller.rb
class Character::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(name: params[:item][:name], description: params[:item][:description])
    @item.character_id = params[:id]
    if @item.save
      redirect_to character_path(Character.find(params[:id]))
    else
      render :new
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :description)
  end
end

app/controllers/character/powers_controller.rb
class PowersController < ApplicationController
  def new
    @power = Power.new
  end

  def create
    @power = Power.new(power_params)
  end

  private

  def power_params
    params.require(:power).permit(:name, :description)
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def index
    @characters = Character.all
  end

  def new
    @character = Character.new
  end

  def create
    @character = Character.new(character_params)
    if @character.save
      redirect_to root_path
    else
      flash[:errors] = "Invalid fields"
      render :new
    end
  end

  def show
    @character = Character.find(params[:id])
  end

  def destroy
    @character = Character.find(params[:id])
    @character.destroy
    redirect_to root_path
  end

  private

  def character_params
    params.require(:character).permit(:name, :race, :character_class, :gender)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
  end

  private

  def item_params
    params.require(:item).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/powers_helper.rb
module PowersHelper
end

app/views/character/items/new.html.erb
<%= form_for  [:character, @item] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.submit %>
<% end %>

app/views/characters/index.html.erb
<% @characters.each do |char| %>
  <p><%= link_to char.name, character_path(char) %>
    <%= link_to "X", character_path(char), method: "delete" %>
</p>
<% end %>
<a href="/characters/new">New Character</a>

app/views/characters/new.html.erb
<%= form_for @character do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :gender %>
  <%= f.text_field :gender %>
  <%= f.label :race %>
  <%= f.text_field :race %>
  <%= f.label "Class" %>
  <%= f.text_field :character_class %>
  <%= f.submit %>
<% end %>

app/views/characters/show.html.erb
<p><%= @character.name %></p>
<p><%= @character.gender %>
<%= @character.race %>
<%= @character.character_class %></p>
<% @character.items.each do |item| %>
  <p><%= item.name %>
<em><%= item.description %></em></p>
<% end %>
<%= link_to "Add Power", character_new_power_path %>
<%= link_to "Add Item", character_new_item_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CharacterSheet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>